### ISSUE TITLE
Lack of look-ahead in elisp regexp and related difficulties.

### ISSUE THREAD

**Issue by Fuco1** [skeeto/rdp#1]
I am trying to write a parser which looks for `$<number>` in strings.  I would need something like "eat everything up to the first $" but _without_ consuming the $ char because then you can't match the number field with a rule like `"\\$" number`.

How would you express look-ahead logic in this parser?  Right now I use a hack to match `[^$]+` but it's not going to work with more complex expressions.

**Comment by Fuco1** [comment]
For example in Haskell parser library `parsec` there are two combinators `manyTill` and `lookAhead` which try to match a rule but do not consume it to end a repeated match.

Do you think it would be simple/possible to add such combinators here?  Other combinators like `many` (acting like `*` in RE) or `many1` (acting like `+`) could be implemented as well.

See: https://hackage.haskell.org/package/parsec-3.0.0/docs/Text-Parsec-Combinator.html#v:manyTill

**Comment by skeeto** [comment]
I think this similar to how Emacs' font locking sometimes needs to match
things that won't actually get highlighted. That's accomplished with
groups and telling font lock which groups get highlighted. Perhaps
similarly rdp could accept a regexp/number pair to limit what it
consumes -- stop at the end of the specified group? Or maybe skip the
group number all together and just stop at the end of the last non-shy
group.

I wonder if a noflet rdp-skip-whitespace rebind hack could accomplish
what you need, but that's pretty flaky.

Sorry that my little parser sucks! It simply may not be up to the task.
I wrote it a few years ago to accomplish a few specific things, since
the alternatives (SMIE) couldn't quite do what I wanted, and in
retrospect I think it could be a lot better (no global state, overall
better API design).

**Comment by Fuco1** [comment]
Hah, no worries.

I like the group idea, that might actually work quite well in practice.  I've managed to write the grammar for my particular problem too, I just had to think a bit harder on how to express it without the need of look-ahead.

In the meantime I wrote my own port of parsec :D But I have yet to test how slow it is (as it makes heavy use of closures, which aren't all the awesome  in emacs yet).  Certainly it won't be able to run indentation, but for small DSLs it should do.

I might try to write the group support if I find the time and provide a PR.
