### ISSUE TITLE
Segfault on parse

### ISSUE THREAD

**Issue by hinrik** [skeeto/rdp#2]
Hi. First of all, I couldn't get `rdp-parse-string` to run without increasing the values of `max-specdl-size` and `max-lisp-eval-depth` a lot. But when they were high enough, emacs started segfaulting instead. Here is the code:

``` elisp
(require 'rdp)

(defvar tokens
  `((variable     sigil [twigil empty] variable-name)
    (sigil         . ,(rx-to-string `(1+ (char "@$%&"))))
    (twigil        . ,(rx-to-string `(char ".^*?=!~:")))
    (identifier    . ,(rx-to-string `(and (regex "[_[:alpha:]]")
                                          (0+ (regex "[_[:alnum:]]"))
                                          (0+ (any "-'") (regex "[_[:alpha:]]") (0+ (regex "[_[:alnum:]]"))))))
    (special-var   . ,(rx-to-string `(or digit (char "/!¢"))))
    (variable-name [special-var identifier])))

(defvar functions
  `((variable . ,(lambda (e) (message "got a variable")))))

(let ((max-lisp-eval-depth
       (floor (* 100 max-lisp-eval-depth)))
      (max-specpdl-size
       (floor (* 100 max-specpdl-size))))
  (rdp-parse-string "$foo" tokens functions))
```

**Comment by skeeto** [comment]
If rdp blowing the default stack, either you're parsing something very
complex -- certaintly not the case here -- or you have left-recursion in
your grammar. You probably know this already: it happens when a token
can reach itself recursively without consuming input. In your case, it's
that "empty" token. Since it's not in the token alist, rdp treats it as
an empty list.

The solution is to add "empty" to match an empty regular expression,
just like no-prod and no-sum in the documentation example. You use it
but don't define it.

```
(empty    . "")
```

As I think more about it, logically this should be exactly equivalent to
an empty list (which should also always match), meaning this is probably
a bug of some sort. For reasons I can't remember, a regexp is required
in order to be proper terminal, and otherwise the parser doesn't match
"empty" properly. When I added that token, your example worked for me.

Final note: I'm not surprised about the crashing. Greatly increasing
those two variables is one of the few legit ways to crash Emacs from
Elisp (another is executing custom, invalid bytecode). Here's a simple,
self-contained example:

```
(let ((max-lisp-eval-depth (* 100 max-lisp-eval-depth))
      (max-specpdl-size (* 100 max-specpdl-size))
      (foo (lambda () (funcall foo))))
  (funcall foo))
```

**Comment by hinrik** [comment]
I did indeed forget to define the 'empty' token. Thanks for the explanation.
